x-healthcheck_conf: &healthcheck_conf
      interval: 5s
      retries: 30

services:
  nodejs_nest_is_working:
    build:
      dockerfile: Dockerfile
      args:
        - TAG=${TAG:-edge}
    environment:
      - NJCLITOOL=@nestjs/cli
      - NJRUNCMD=npm run start
      - DOCKER_DEBUG=1
    volumes:
      - ./rsc/test_project/nestjs:/src/project:rw
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000"]
      <<: *healthcheck_conf

  nodejs_angular_is_working:
    build:
      dockerfile: Dockerfile
      args:
        - TAG=${TAG:-edge}
    environment:
      - NJCLITOOL=@angular/cli
      - NJRUNCMD=npm run start
      - DOCKER_DEBUG=1
    volumes:
      - ./rsc/test_project/angular:/src/project:rw
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4200"]
      <<: *healthcheck_conf
