#!/bin/ash

# Hard core mode
## -e			Exit immediately if a command exits with a non-zero status.
## -u			Treat unset variables as an error.
## -o pipefail	The return value of a pipeline is the status of the last command
## 				to exit with a non-zero status, or zero if no command exited
##				with a non-zero status.
set -eu -o pipefail

# ANSI escape codes
ESC="\x1b"
CSI="${ESC}["
RST="${CSI}0m"

RED="${CSI}31m"
GRE="${CSI}32m"
BLU="${CSI}34m"

# Service name
SERVICE_NAME="${GRE}NodeJS${RST}"
# Service version
SERVICE_NAME="${SERVICE_NAME} (${BLU}$(node --version)${RST})"

# Debugging information
if [ "${DOCKER_DEBUG}" != "" ]; then
	printf "debuging %b\n\n" "${SERVICE_NAME}"
	# Print environment variables
	printf "NJCLITOOL     %b\n" "${NJCLITOOL}"
	printf "NJRUNCMD      %b\n" "${NJRUNCMD}"
	printf "DOCKER_DEBUG  %b\n\n" "${DOCKER_DEBUG}"
fi

# Initialize the service only if not already initialized
if [ ! -f "${PWD}/node_modules" ]; then
	npm update
	npm upgrade
	npm install --global "${NJCLITOOL}"
else
	printf "%b %b, Skiping initialization\n" "${SERVICE_NAME}" "${GRE}found${RST}"
fi

printf "%b launched\n" "${SERVICE_NAME}"

# Execute the service
exec ${NJRUNCMD}
